platform :ios, '11.0'
source 'git@github.com:NativoPlatform/CocoaPods-Private-Specs.git'
source 'https://cdn.cocoapods.org/'

target 'Nativo Ads' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NativoSwiftTableViewSample
  pod 'NativoSDK', '~> 7.1.0-alpha.5'

end
