platform :ios, '14.0'
source 'https://cdn.cocoapods.org/'
source 'git@github.com:NativoPlatform/CocoaPods-Private-Specs.git'

target 'Nativo Ads' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NativoSwiftTableViewSample
  pod 'NativoSDK', '~> 7.2.0-alpha.9'

end
