platform :ios, '11.0'
source 'https://cdn.cocoapods.org/'
source 'git@github.com:NativoPlatform/CocoaPods-Private-Specs.git'


target 'CollectionDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CollectionDemo
  pod 'NativoSDK', '~> 7.1.0-alpha.23'
  pod 'GoogleAds-IMA-iOS-SDK', '3.13.0'

end
