platform :ios, '14.0'
source 'https://cdn.cocoapods.org/'

target 'CollectionDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CollectionDemo
  pod 'NativoSDK'
  pod 'GoogleAds-IMA-iOS-SDK', '3.23.0'

end
