platform :ios, '11.0'
source 'https://cdn.cocoapods.org/'


target 'CollectionDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CollectionDemo
  pod 'NativoSDK', '7.0.0'
  pod 'GoogleAds-IMA-iOS-SDK', '3.13.0'

end
