platform :ios, '11.0'
source 'https://cdn.cocoapods.org/'
source 'git@github.com:NativoPlatform/CocoaPods-Private-Specs.git'

target 'NativoGAMIntegrationSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NativoSwiftTableViewSample
  pod 'NativoSDK', '~> 7.0.0-alpha.20'
  pod 'Google-Mobile-Ads-SDK', '~> 8.8.0'
  pod 'GoogleAds-IMA-iOS-SDK', '~> 3.13.0'

end
